# Generated by Django 4.2.1 on 2023-05-20 00:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="buy",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
        migrations.AlterField(
            model_name="rate",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
