# Generated by Django 4.2.1 on 2023-05-20 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0002_alter_rate_buy_alter_rate_date_alter_rate_sell"),
    ]

    operations = [
        migrations.CreateModel(
            name="Search",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_a", models.CharField(max_length=3)),
                ("currency_b", models.CharField(max_length=3)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddConstraint(
            model_name="search",
            constraint=models.UniqueConstraint(
                fields=("currency_a", "currency_b"), name="unique_search"
            ),
        ),
    ]
