# Generated by Django 4.2.1 on 2023-05-20 01:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0003_search_search_unique_search"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="search",
            name="unique_search",
        ),
    ]
