# Generated by Django 4.2.1 on 2023-05-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0004_remove_search_unique_search"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="buy",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name="rate",
            name="sell",
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
