# Generated by Django 4.2.1 on 2023-05-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0005_alter_rate_buy_alter_rate_sell"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="amount",
            field=models.DecimalField(decimal_places=10, default=None, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="search",
            name="currency_a",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="search",
            name="currency_b",
            field=models.CharField(max_length=4),
        ),
    ]
