# Generated by Django 4.2.1 on 2023-05-23 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0006_search_amount_alter_search_currency_a_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Search",
        ),
    ]
